# -*- coding: utf-8 -*-
"""Scrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PzS75yNf5LykjdX16IpEngb5DZOEOPly
"""

import requests
from bs4 import BeautifulSoup

url="https://www.worldatlas.com/articles/the-7-wonders-of-the-world.html"
response= requests.get(url)

help(response)

response

get = BeautifulSoup(response.text,"html.parser")

get

help(get)

get.p

para=get.p.text

a=get.findAll('p')

type(a)

arr=[]
for i in a:
    print(i.text)
    arr.append(i.text)

print(len(arr))

"""# 2"""

url="https://www.icc-cricket.com/rankings/mens/team-rankings/test"
response= requests.get(url)

response

res=BeautifulSoup(response.text,"html.parser")

res

table= res.find('div',"rankings-block__container rankings-table")

type(table)

table

"""# Images"""

import requests
import urllib.request as ureq
from bs4 import BeautifulSoup

url = 'https://yts.lt/browse-movies/0/all/all/0/year'
response = requests.get(url)
response



res=BeautifulSoup(response.text,"html.parser")

res

print(res.prettify())

photos= res.findAll('div','browse-movie-wrap col-xs-10 col-sm-4 col-md-5 col-lg-4')

photos

for i in photos:
    a=i.find('figure')
    url_img=a.img['src']
    name=url_img.split('/')
    name=name[-2]+"_"+name[-1]
    ureq.urlretrieve(url_img,name)
    print(url_img)
    break

"""# StackOverflow"""

